name: Code Signing

on:
  push: 
    branches: master

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 14.18.1
      - name: Npm install
        run: npm install --build-from-resource

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          build_script_name: 'nocopybuild:prod && npx electron-builder build --windows'
          github_token: ${{ secrets.TOKEN }}

          windows_certs: ${{ secrets.CODESIGN }}
          windows_certs_password: ${{ secrets.PASSWORD }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
