name: Node CI

on:
  push: 
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14.18.1
    - name: Install NPM packages
      run: npm install
    - name: Build website
      run: ng build --configuration production --base-href \"https://frameweb.structuralengine.com/\"
    - name: Deploy 
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        BRANCH: gh-pages
        FOLDER: dist
        CLEAN: true
